# Generated by Django 4.1.7 on 2023-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateTimeField(verbose_name='expiration date')),
                ('holder', models.CharField(max_length=500, verbose_name='holder')),
                ('number', models.CharField(max_length=500, verbose_name='number')),
                ('cvv', models.IntegerField(max_length=4, verbose_name='cvv')),
            ],
        ),
    ]
