# Generated by Django 4.1.7 on 2023-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0003_alter_creditcard_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.IntegerField(blank=True, null=True, verbose_name='cvv'),
        ),
    ]
