# Generated by Django 4.1.7 on 2023-03-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard_api', '0002_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='exp_date',
            field=models.DateField(verbose_name='expiration date'),
        ),
    ]
