# Generated by Django 4.1.7 on 2023-03-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard_api', '0004_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='brand',
            field=models.CharField(default='visa', max_length=100, verbose_name='brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.IntegerField(null=True, verbose_name='cvv'),
        ),
    ]
