# Generated by Django 4.1.7 on 2023-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard_api', '0005_creditcard_brand_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name='brand'),
        ),
    ]
